_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "x65.pkl"
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [128, 128, 128]
  BACKBONE:
    NAME: "d2_xception_65"
  RESNETS:
    NORM: "SyncBN"
    RES4_DILATION: 1
    RES5_DILATION: 2
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  MAX_ITER: 90000
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (512, 1024)
