defaults:
    - default
    - data: kitti_360
    - _self_

name: "kitti_360"
model: "bts"
output_path: "out/kitti_360"

num_epochs: 60
# batch_size: 16
batch_size: 1

use_backbone: true

# set the segmentation_mode on this level; it is automatically copied down
# segmentation_mode: "KITTI-360"
segmentation_mode: 'panoptic_deeplab'

save_best:
    metric: abs_rel
    sign: -1

data:
    data_fc: 2
    image_size: [192, 640]
    color_aug: true
    is_preprocessed: true
    fisheye_rotation: [0, -15]

model_conf:
    arch: "BTSNet"
    use_code: true
    prediction_mode: default

    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true

    encoder:
        type: "monodepth2"
        freeze: false
        pretrained: true
        resnet_layers: 50
        num_ch_dec: [32,32,64,128,256]
        d_out: 64

    mlp_coarse:
        type : "resnet"
        n_blocks : 0
        d_hidden : 64

    mlp_fine:
        type : "empty"
        n_blocks : 1
        d_hidden : 128

    # NEW: for the segmentation mlp
    mlp_segmentation:
        type: "resnet"
        n_blocks: 0
        d_hidden: 64

    z_near: 3
    z_far: 80
    inv_z: true

    n_frames_encoder: 1
    n_frames_render: 2
    frame_sample_mode: kitti360-mono

    sample_mode: patch
    patch_size: 8
    ray_batch_size: 4096

    flip_augmentation: true

    learn_empty: false
    code_mode: z

loss:
    criterion: "l1+ssim"
    invalid_policy: weight_guided
    lambda_edge_aware_smoothness: 0.001
    lambda_segmentation: 0.02
    lambda_density_entropy: 0
#    segmentation_class_weights: # assuming cityscapes labels
#        0: 1 # 'road'
#        1: 1 # 'sidewalk'
#        2: 1 # 'building'
#        3: 1 # 'wall'
#        4: 1 # 'fence'
#        5: 1 # 'pole'
#        6: 1 # 'traffic light'
#        7: 1 # 'traffic sign'
#        8: 1 # 'vegetation'
#        9: 1 # 'terrain'
#        10: 1 # 'sky'
#        11: 1 # 'person'
#        12: 1 # 'rider'
#        13: 1 # 'car'
#        14: 1 # 'truck'
#        15: 1 # 'bus'
#        16: 1 # 'train'
#        17: 1 # 'motorcycle'
#        18: 1 # 'bicycle'

    segmentation_class_weights: # assuming cityscapes labels
        0: 1 # 'road'
        1: 10 # 'sidewalk'
        2: 1 # 'building'
        3: 1 # 'wall'
        4: 1 # 'fence'
        5: 10 # 'pole'
        6: 5 # 'traffic light'
        7: 10 # 'traffic sign'
        8: 1 # 'vegetation'
        9: 1 # 'terrain'
        10: 1 # 'sky'
        11: 5 # 'person'
        12: 1 # 'rider'
        13: 1 # 'car'
        14: 1 # 'truck'
        15: 1 # 'bus'
        16: 1 # 'train'
        17: 1 # 'motorcycle'
        18: 1 # 'bicycle'

scheduler:
    type: step
    step_size: 120000
    gamma: 0.1

renderer:
    n_coarse : 64
    n_fine : 0
    n_fine_depth : 0
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    hard_alpha_cap: true
    eval_batch_size: 200000
